// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rmocchy/convinient_wire/sample/basic-di/handler"
	"github.com/rmocchy/convinient_wire/sample/basic-di/repository"
	"github.com/rmocchy/convinient_wire/sample/basic-di/service"
)

// Injectors from wire.go:

// InitializeUserHandler は全ての依存関係を解決してUserHandlerを初期化
func InitializeUserHandler() *handler.UserHandler {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}
