// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rmocchy/convinient_wire/sample/basic/handler"
	"github.com/rmocchy/convinient_wire/sample/basic/repository"
	"github.com/rmocchy/convinient_wire/sample/basic/service"
)

// Injectors from wire.go:

// InitializeUserHandler は全ての依存関係を解決してUserHandlerを初期化
func InitializeUserHandler() (*ControllerSet, error) {
	userRepository, err := repository.NewUserRepository()
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	controllerSet := &ControllerSet{
		handler: userHandler,
	}
	return controllerSet, nil
}

// wire.go:

type ControllerSet struct {
	handler *handler.UserHandler
}
